// Report Export Utility with Customizable Templates

export type ExportFormat = 'csv' | 'json'
export type ReportType = 'sales' | 'top-products' | 'combined'

export interface ExportOptions {
  format: ExportFormat
  reportType: ReportType
  includeHeader?: boolean
  includeFooter?: boolean
  companyName?: string
  customHeader?: string
  customFooter?: string
  dateFormat?: string
}

export interface SalesData {
  sale_date: string
  total_transactions: number
  total_revenue: string
}

export interface TopProductData {
  product_id: number
  product_name: string
  sku?: string
  total_qty_sold: number
  total_revenue: string
}

// Template untuk CSV Export
export function exportToCSV(
  salesData: SalesData[],
  topProductsData: TopProductData[],
  options: ExportOptions,
  from: string,
  to: string
) {
  let csv = ''

  // Header Template (Customizable)
  if (options.includeHeader !== false) {
    const companyName = options.companyName || 'POS System'
    const customHeader = options.customHeader || ''
    const reportTitle = options.reportType === 'sales' 
      ? 'Sales Report' 
      : options.reportType === 'top-products'
      ? 'Top Products Report'
      : 'Combined Sales Report'
    
    csv += `${companyName}\n`
    if (customHeader) csv += `${customHeader}\n`
    csv += `${reportTitle}\n`
    csv += `Period: ${from} to ${to}\n`
    csv += `Generated: ${new Date().toLocaleString()}\n`
    csv += '\n'
  }

  // Sales Data Section
  if (options.reportType === 'sales' || options.reportType === 'combined') {
    csv += 'SALES BY DATE\n'
    csv += 'Date,Transactions,Revenue\n'
    
    salesData.forEach((sale) => {
      const date = sale.sale_date
      const transactions = sale.total_transactions
      const revenue = parseFloat(sale.total_revenue).toFixed(2)
      csv += `${date},${transactions},Rp ${parseFloat(sale.total_revenue).toLocaleString('id-ID')}\n`
    })
    
    // Summary
    const totalTransactions = salesData.reduce((sum, s) => sum + s.total_transactions, 0)
    const totalRevenue = salesData.reduce((sum, s) => sum + parseFloat(s.total_revenue), 0)
    csv += `\nTOTAL,${totalTransactions},Rp ${totalRevenue.toLocaleString('id-ID', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}\n`
    csv += '\n'
  }

  // Top Products Section
  if (options.reportType === 'top-products' || options.reportType === 'combined') {
    csv += 'TOP PRODUCTS\n'
    csv += 'Product Name,SKU,Quantity Sold,Revenue\n'
    
    topProductsData.forEach((product) => {
      const name = `"${product.product_name}"` // Quote untuk handle comma di nama
      const sku = product.sku || '-'
      const qty = product.total_qty_sold
      const revenue = parseFloat(product.total_revenue).toFixed(2)
      csv += `${name},${sku},${qty},Rp ${parseFloat(product.total_revenue).toLocaleString('id-ID')}\n`
    })
    
    // Summary
    const totalQty = topProductsData.reduce((sum, p) => sum + p.total_qty_sold, 0)
    const totalRevenue = topProductsData.reduce((sum, p) => sum + parseFloat(p.total_revenue), 0)
    csv += `\nTOTAL,,"${totalQty}",Rp ${totalRevenue.toLocaleString('id-ID', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}\n`
    csv += '\n'
  }

  // Footer Template (Customizable)
  if (options.includeFooter !== false) {
    const customFooter = options.customFooter || ''
    if (customFooter) {
      csv += `${customFooter}\n`
    }
    csv += `\nReport generated by POS System\n`
  }

  // Download file
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = window.URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  
  const filename = options.reportType === 'sales'
    ? `sales-report-${from}-${to}.csv`
    : options.reportType === 'top-products'
    ? `top-products-report-${from}-${to}.csv`
    : `combined-report-${from}-${to}.csv`
  
  link.download = filename
  link.click()
  window.URL.revokeObjectURL(url)
}

// Template untuk JSON Export
export function exportToJSON(
  salesData: SalesData[],
  topProductsData: TopProductData[],
  options: ExportOptions,
  from: string,
  to: string
) {
  const report: any = {}

  // Header/Metadata
  if (options.includeHeader !== false) {
    report.metadata = {
      companyName: options.companyName || 'POS System',
      reportType: options.reportType,
      period: {
        from,
        to,
      },
      generatedAt: new Date().toISOString(),
      customHeader: options.customHeader || null,
    }
  }

  // Sales Data
  if (options.reportType === 'sales' || options.reportType === 'combined') {
    report.sales = {
      data: salesData.map((s) => ({
        date: s.sale_date,
        transactions: s.total_transactions,
        revenue: parseFloat(s.total_revenue),
      })),
      summary: {
        totalTransactions: salesData.reduce((sum, s) => sum + s.total_transactions, 0),
        totalRevenue: salesData.reduce((sum, s) => sum + parseFloat(s.total_revenue), 0),
      },
    }
  }

  // Top Products Data
  if (options.reportType === 'top-products' || options.reportType === 'combined') {
    report.topProducts = {
      data: topProductsData.map((p) => ({
        productId: p.product_id,
        productName: p.product_name,
        sku: p.sku || null,
        quantitySold: p.total_qty_sold,
        revenue: parseFloat(p.total_revenue),
      })),
      summary: {
        totalQuantitySold: topProductsData.reduce((sum, p) => sum + p.total_qty_sold, 0),
        totalRevenue: topProductsData.reduce((sum, p) => sum + parseFloat(p.total_revenue), 0),
      },
    }
  }

  // Footer
  if (options.includeFooter !== false) {
    report.footer = {
      customFooter: options.customFooter || null,
      generatedBy: 'POS System',
    }
  }

  // Download file
  const json = JSON.stringify(report, null, 2)
  const blob = new Blob([json], { type: 'application/json;charset=utf-8;' })
  const url = window.URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  
  const filename = options.reportType === 'sales'
    ? `sales-report-${from}-${to}.json`
    : options.reportType === 'top-products'
    ? `top-products-report-${from}-${to}.json`
    : `combined-report-${from}-${to}.json`
  
  link.download = filename
  link.click()
  window.URL.revokeObjectURL(url)
}

// Main export function
export function exportReport(
  salesData: SalesData[],
  topProductsData: TopProductData[],
  options: ExportOptions,
  from: string,
  to: string
) {
  if (options.format === 'csv') {
    exportToCSV(salesData, topProductsData, options, from, to)
  } else if (options.format === 'json') {
    exportToJSON(salesData, topProductsData, options, from, to)
  }
}

