// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustInventoryQty = `-- name: AdjustInventoryQty :one
UPDATE inventory
SET qty = qty + $2, updated_at = now()
WHERE product_id = $1
RETURNING id, product_id, qty, updated_at
`

type AdjustInventoryQtyParams struct {
	ProductID pgtype.Int4 `json:"product_id"`
	Qty       int32       `json:"qty"`
}

func (q *Queries) AdjustInventoryQty(ctx context.Context, arg AdjustInventoryQtyParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, adjustInventoryQty, arg.ProductID, arg.Qty)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventory (product_id, qty)
VALUES ($1, $2)
RETURNING id, product_id, qty, updated_at
`

type CreateInventoryParams struct {
	ProductID pgtype.Int4 `json:"product_id"`
	Qty       int32       `json:"qty"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.ProductID, arg.Qty)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryByProduct = `-- name: GetInventoryByProduct :one
SELECT id, product_id, qty, updated_at FROM inventory
WHERE product_id = $1 LIMIT 1
`

func (q *Queries) GetInventoryByProduct(ctx context.Context, productID pgtype.Int4) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByProduct, productID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}

const getLowStockItems = `-- name: GetLowStockItems :many
SELECT i.id, i.product_id, i.qty, i.updated_at, p.name as product_name, p.sku, p.unit
FROM inventory i
JOIN products p ON i.product_id = p.id
WHERE i.qty <= $1
ORDER BY i.qty ASC
`

type GetLowStockItemsRow struct {
	ID          int32              `json:"id"`
	ProductID   pgtype.Int4        `json:"product_id"`
	Qty         int32              `json:"qty"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProductName string             `json:"product_name"`
	Sku         pgtype.Text        `json:"sku"`
	Unit        pgtype.Text        `json:"unit"`
}

func (q *Queries) GetLowStockItems(ctx context.Context, qty int32) ([]GetLowStockItemsRow, error) {
	rows, err := q.db.Query(ctx, getLowStockItems, qty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLowStockItemsRow{}
	for rows.Next() {
		var i GetLowStockItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Qty,
			&i.UpdatedAt,
			&i.ProductName,
			&i.Sku,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventory = `-- name: ListInventory :many
SELECT i.id, i.product_id, i.qty, i.updated_at, p.name as product_name, p.sku, p.unit
FROM inventory i
JOIN products p ON i.product_id = p.id
ORDER BY p.name
`

type ListInventoryRow struct {
	ID          int32              `json:"id"`
	ProductID   pgtype.Int4        `json:"product_id"`
	Qty         int32              `json:"qty"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProductName string             `json:"product_name"`
	Sku         pgtype.Text        `json:"sku"`
	Unit        pgtype.Text        `json:"unit"`
}

func (q *Queries) ListInventory(ctx context.Context) ([]ListInventoryRow, error) {
	rows, err := q.db.Query(ctx, listInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryRow{}
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Qty,
			&i.UpdatedAt,
			&i.ProductName,
			&i.Sku,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryQty = `-- name: UpdateInventoryQty :one
UPDATE inventory
SET qty = $2, updated_at = now()
WHERE product_id = $1
RETURNING id, product_id, qty, updated_at
`

type UpdateInventoryQtyParams struct {
	ProductID pgtype.Int4 `json:"product_id"`
	Qty       int32       `json:"qty"`
}

func (q *Queries) UpdateInventoryQty(ctx context.Context, arg UpdateInventoryQtyParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryQty, arg.ProductID, arg.Qty)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Qty,
		&i.UpdatedAt,
	)
	return i, err
}
