// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Inventory struct {
	ID        int32              `json:"id"`
	ProductID pgtype.Int4        `json:"product_id"`
	Qty       int32              `json:"qty"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID         int32              `json:"id"`
	Sku        pgtype.Text        `json:"sku"`
	Name       string             `json:"name"`
	CategoryID pgtype.Int4        `json:"category_id"`
	Price      pgtype.Numeric     `json:"price"`
	CostPrice  pgtype.Numeric     `json:"cost_price"`
	Unit       pgtype.Text        `json:"unit"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Sale struct {
	ID            int32              `json:"id"`
	InvoiceNo     string             `json:"invoice_no"`
	UserID        pgtype.Int4        `json:"user_id"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	PaidAmount    pgtype.Numeric     `json:"paid_amount"`
	ChangeAmount  pgtype.Numeric     `json:"change_amount"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SaleItem struct {
	ID        int32          `json:"id"`
	SaleID    pgtype.Int4    `json:"sale_id"`
	ProductID pgtype.Int4    `json:"product_id"`
	Qty       int32          `json:"qty"`
	Price     pgtype.Numeric `json:"price"`
	Discount  pgtype.Numeric `json:"discount"`
	Subtotal  pgtype.Numeric `json:"subtotal"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
