// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (sku, name, category_id, price, cost_price, unit)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, sku, name, category_id, price, cost_price, unit, created_at
`

type CreateProductParams struct {
	Sku        pgtype.Text    `json:"sku"`
	Name       string         `json:"name"`
	CategoryID pgtype.Int4    `json:"category_id"`
	Price      pgtype.Numeric `json:"price"`
	CostPrice  pgtype.Numeric `json:"cost_price"`
	Unit       pgtype.Text    `json:"unit"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.CategoryID,
		arg.Price,
		arg.CostPrice,
		arg.Unit,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.CostPrice,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT p.id, p.sku, p.name, p.category_id, p.price, p.cost_price, p.unit, p.created_at, c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.id = $1 LIMIT 1
`

type GetProductByIDRow struct {
	ID           int32              `json:"id"`
	Sku          pgtype.Text        `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int4        `json:"category_id"`
	Price        pgtype.Numeric     `json:"price"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	Unit         pgtype.Text        `json:"unit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetProductByID(ctx context.Context, id int32) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.CostPrice,
		&i.Unit,
		&i.CreatedAt,
		&i.CategoryName,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT p.id, p.sku, p.name, p.category_id, p.price, p.cost_price, p.unit, p.created_at, c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.sku = $1 LIMIT 1
`

type GetProductBySKURow struct {
	ID           int32              `json:"id"`
	Sku          pgtype.Text        `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int4        `json:"category_id"`
	Price        pgtype.Numeric     `json:"price"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	Unit         pgtype.Text        `json:"unit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetProductBySKU(ctx context.Context, sku pgtype.Text) (GetProductBySKURow, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i GetProductBySKURow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.CostPrice,
		&i.Unit,
		&i.CreatedAt,
		&i.CategoryName,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.sku, p.name, p.category_id, p.price, p.cost_price, p.unit, p.created_at, c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
ORDER BY p.created_at DESC
`

type ListProductsRow struct {
	ID           int32              `json:"id"`
	Sku          pgtype.Text        `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int4        `json:"category_id"`
	Price        pgtype.Numeric     `json:"price"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	Unit         pgtype.Text        `json:"unit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.Price,
			&i.CostPrice,
			&i.Unit,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithStock = `-- name: ListProductsWithStock :many
SELECT p.id, p.sku, p.name, p.category_id, p.price, p.cost_price, p.unit, p.created_at, c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
INNER JOIN inventory i ON p.id = i.product_id
WHERE i.qty > 0
ORDER BY p.created_at DESC
`

type ListProductsWithStockRow struct {
	ID           int32              `json:"id"`
	Sku          pgtype.Text        `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int4        `json:"category_id"`
	Price        pgtype.Numeric     `json:"price"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	Unit         pgtype.Text        `json:"unit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListProductsWithStock(ctx context.Context) ([]ListProductsWithStockRow, error) {
	rows, err := q.db.Query(ctx, listProductsWithStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsWithStockRow{}
	for rows.Next() {
		var i ListProductsWithStockRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.Price,
			&i.CostPrice,
			&i.Unit,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT p.id, p.sku, p.name, p.category_id, p.price, p.cost_price, p.unit, p.created_at, c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.name ILIKE '%' || $1 || '%' OR p.sku ILIKE '%' || $1 || '%'
ORDER BY p.name
`

type SearchProductsRow struct {
	ID           int32              `json:"id"`
	Sku          pgtype.Text        `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int4        `json:"category_id"`
	Price        pgtype.Numeric     `json:"price"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	Unit         pgtype.Text        `json:"unit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) SearchProducts(ctx context.Context, dollar_1 pgtype.Text) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsRow{}
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.Price,
			&i.CostPrice,
			&i.Unit,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET sku = $2, name = $3, category_id = $4, price = $5, cost_price = $6, unit = $7
WHERE id = $1
RETURNING id, sku, name, category_id, price, cost_price, unit, created_at
`

type UpdateProductParams struct {
	ID         int32          `json:"id"`
	Sku        pgtype.Text    `json:"sku"`
	Name       string         `json:"name"`
	CategoryID pgtype.Int4    `json:"category_id"`
	Price      pgtype.Numeric `json:"price"`
	CostPrice  pgtype.Numeric `json:"cost_price"`
	Unit       pgtype.Text    `json:"unit"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.CategoryID,
		arg.Price,
		arg.CostPrice,
		arg.Unit,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.CostPrice,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}
