// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdjustInventoryQty(ctx context.Context, arg AdjustInventoryQtyParams) (Inventory, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetInventoryByProduct(ctx context.Context, productID pgtype.Int4) (Inventory, error)
	GetLowStockItems(ctx context.Context, qty int32) ([]GetLowStockItemsRow, error)
	GetProductByID(ctx context.Context, id int32) (GetProductByIDRow, error)
	GetProductBySKU(ctx context.Context, sku pgtype.Text) (GetProductBySKURow, error)
	GetSaleByID(ctx context.Context, id int32) (GetSaleByIDRow, error)
	GetSaleByInvoice(ctx context.Context, invoiceNo string) (GetSaleByInvoiceRow, error)
	GetSaleItemsByProductID(ctx context.Context, productID pgtype.Int4) ([]GetSaleItemsByProductIDRow, error)
	GetSaleItemsBySaleID(ctx context.Context, saleID pgtype.Int4) ([]GetSaleItemsBySaleIDRow, error)
	GetSalesStats(ctx context.Context, arg GetSalesStatsParams) (GetSalesStatsRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListInventory(ctx context.Context) ([]ListInventoryRow, error)
	ListProducts(ctx context.Context) ([]ListProductsRow, error)
	ListProductsWithStock(ctx context.Context) ([]ListProductsWithStockRow, error)
	ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error)
	ListSalesByDateRange(ctx context.Context, arg ListSalesByDateRangeParams) ([]ListSalesByDateRangeRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	SalesByDate(ctx context.Context, arg SalesByDateParams) ([]SalesByDateRow, error)
	SalesByPaymentMethod(ctx context.Context, arg SalesByPaymentMethodParams) ([]SalesByPaymentMethodRow, error)
	SearchProducts(ctx context.Context, dollar_1 pgtype.Text) ([]SearchProductsRow, error)
	TopProducts(ctx context.Context, arg TopProductsParams) ([]TopProductsRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateInventoryQty(ctx context.Context, arg UpdateInventoryQtyParams) (Inventory, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
