// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sale_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (sale_id, product_id, qty, price, discount, subtotal)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, sale_id, product_id, qty, price, discount, subtotal
`

type CreateSaleItemParams struct {
	SaleID    pgtype.Int4    `json:"sale_id"`
	ProductID pgtype.Int4    `json:"product_id"`
	Qty       int32          `json:"qty"`
	Price     pgtype.Numeric `json:"price"`
	Discount  pgtype.Numeric `json:"discount"`
	Subtotal  pgtype.Numeric `json:"subtotal"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.Qty,
		arg.Price,
		arg.Discount,
		arg.Subtotal,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.Qty,
		&i.Price,
		&i.Discount,
		&i.Subtotal,
	)
	return i, err
}

const getSaleItemsByProductID = `-- name: GetSaleItemsByProductID :many
SELECT si.id, si.sale_id, si.product_id, si.qty, si.price, si.discount, si.subtotal, s.invoice_no, s.created_at as sale_date
FROM sale_items si
JOIN sales s ON si.sale_id = s.id
WHERE si.product_id = $1
ORDER BY s.created_at DESC
`

type GetSaleItemsByProductIDRow struct {
	ID        int32              `json:"id"`
	SaleID    pgtype.Int4        `json:"sale_id"`
	ProductID pgtype.Int4        `json:"product_id"`
	Qty       int32              `json:"qty"`
	Price     pgtype.Numeric     `json:"price"`
	Discount  pgtype.Numeric     `json:"discount"`
	Subtotal  pgtype.Numeric     `json:"subtotal"`
	InvoiceNo string             `json:"invoice_no"`
	SaleDate  pgtype.Timestamptz `json:"sale_date"`
}

func (q *Queries) GetSaleItemsByProductID(ctx context.Context, productID pgtype.Int4) ([]GetSaleItemsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getSaleItemsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSaleItemsByProductIDRow{}
	for rows.Next() {
		var i GetSaleItemsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.Qty,
			&i.Price,
			&i.Discount,
			&i.Subtotal,
			&i.InvoiceNo,
			&i.SaleDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSaleItemsBySaleID = `-- name: GetSaleItemsBySaleID :many
SELECT si.id, si.sale_id, si.product_id, si.qty, si.price, si.discount, si.subtotal, p.name as product_name, p.sku
FROM sale_items si
JOIN products p ON si.product_id = p.id
WHERE si.sale_id = $1
ORDER BY si.id
`

type GetSaleItemsBySaleIDRow struct {
	ID          int32          `json:"id"`
	SaleID      pgtype.Int4    `json:"sale_id"`
	ProductID   pgtype.Int4    `json:"product_id"`
	Qty         int32          `json:"qty"`
	Price       pgtype.Numeric `json:"price"`
	Discount    pgtype.Numeric `json:"discount"`
	Subtotal    pgtype.Numeric `json:"subtotal"`
	ProductName string         `json:"product_name"`
	Sku         pgtype.Text    `json:"sku"`
}

func (q *Queries) GetSaleItemsBySaleID(ctx context.Context, saleID pgtype.Int4) ([]GetSaleItemsBySaleIDRow, error) {
	rows, err := q.db.Query(ctx, getSaleItemsBySaleID, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSaleItemsBySaleIDRow{}
	for rows.Next() {
		var i GetSaleItemsBySaleIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.Qty,
			&i.Price,
			&i.Discount,
			&i.Subtotal,
			&i.ProductName,
			&i.Sku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
